productos_ver:
    path:     /productos/ver/{idproducto}
    defaults: { _controller: ProductosManagerBundle:Default:ver , (idproducto:null)}
    
productos_usuario_ver:
    path:     /productos/listarusuario/{idusuario}
    defaults: { _controller: ProductosManagerBundle:Default:listarusuario, (idusuario:null) }