productos_negociacion_ofertar:
    path:     /ofertas/ofertar
    defaults: { _controller: ProductosNegociacionBundle:Default:ofertar }
    methods:  [POST]
    
productos_negociacion_aceptar:
    path:     /ofertas/aceptar
    defaults: { _controller: ProductosNegociacionBundle:Default:rechazarOferta }
    methods:  [POST]
    
productos_negociacion_rechazar:
    path:     /ofertas/rechazar
    defaults: { _controller: ProductosNegociacionBundle:Default:aceptarOferta }
    methods:  [POST]
    
productos_negociacion_ver_ofertas_productos:
    path:     /ofertas/listar/{idproducto}
    defaults: { _controller: ProductosNegociacionBundle:Default:listar, idproducto: null }
    methods:  [GET]