Productos\ManagerBundle\Entity\Usuarios:
    type: entity
    table: usuarios
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idFront:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: id_front
        nombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        fechaRegistro:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: fecha_registro
    lifecycleCallbacks: {  }
