Productos\ManagerBundle\Entity\Usuarios:
    type: entity
    table: usuarios
    id:
        id:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        fechaRegistro:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: fecha_registro
        rutaAvatar:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: ruta_avatar
    lifecycleCallbacks: {  }
